

name: Publish Package Action

on:
  
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
   
    runs-on: ubuntu-latest

    steps:
   
      - uses: actions/checkout@v2
      - run: python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      - run: python setup.py sdist
      - run: twine upload dist/*
      - run: echo "🎉 Triggered by ${{ github.event_name }} event."
      - run: echo "🐧 Running on ${{ runner.os }} server hosted by GitHub!"
      - name: List repository files 
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 Job's status is ${{ job.status }}."
