



university = [
"University of Dar es Salaam UDSM (Dar es Salaam)", 
"Sokoine University of Agriculture SUA (Morogoro)", 
"Open University of Tanzania OUT (Dar es Salaam)", 
"Ardhi University ARU (Dar es Salaam)", 
"State University of Zanzibar SUZA (Zanzibar)",
"Mzumbe University MU (Morogoro)", 
"Muhimbili University of Health & Allied Sciences MUHAS (Dar es Salaam)", 
"Nelson Mandela African Institute of Science and Technology NMAIST (Arusha)",
"University of Dodoma UDOM (Dodoma)" ,
"Mbeya University of Science and Technology MUST (Mbeya) ",
"Moshi Cooperative University MoCU (Moshi)", 
"Mwalimu Julius K. Nyerere University of Agriculture and Technology MJNUAT (Musoma)",
"Hubert Kairuki Memorial University HKMU (Dar es Salaam )",
"International Medical and Technological University IMTU (Dar es Salaam )",
"Tumaini University Makumira TUMA (Arusha) ",
"St. Augustine University of Tanzania SAUT (Mwanza) ",
"Zanzibar University ZU (Zanzibar)", 
"Mount Meru University MMU (Arusha) ",
"University of Arusha UoA (Arusha)", 
"Teofilo Kisanji University TEKU (Mbeya)", 
"Muslim University of Morogoro MUM (Morogoro)", 
"St. John's University of Tanzania SJUT (Dodoma)",
"University of Bagamoyo UoB (Dar es Salaam)",
"Catholic University of Health and Allied Sciences CUHAS (Mwanza) ",
"St. Joseph University in Tanzania SJUIT (Dar es Salaam)",
"United African University of Tanzania UAUT (Dar es Salaam)",
"Sebastian Kolowa Memorial University SEKOMU (Tanga)",
"University of Iringa UoI (Iringa) ",
"AbdulRahman Al-Sumait Memorial University SUMAIT (Zanzibar) ",
"Mwenge Catholic University MWECAU (Moshi)",
"Ruaha Catholic University RUCU (Iringa) ",
"Eckernforde Tanga University ETU (Tanga)" ,
"Aga Khan University AKU (Dar es Salaam )",
"Kampala International University in Tanzania KIUT (Dar es Salaam)",
"Mkwawa University College of Education MUCE University (Iringa)",
"Dar es Salaam University College of Education DUCE University (Dar es Salaam)",
"Mbeya University College of Health and Allied Sciences MUCHAS University (Mbeya)", 
"Kilimanjaro Christian Medical College KCMUCo University (Moshi)",
"Tumaini University Makumira (Dar es Salaam)", 
"Stefano Moshi Memorial University College SMMUCo University (Moshi)",
"Archbishop Mihayo University College of Tabora AMUCTA University (Tabora)",
"St. Francis University College of Health and Allied Sciences SFUCHAS University (Morogoro)", 
"Jordan University College JUCo University (Morogoro)",
"Stella Maris Mtwara University (Mtwara)",
"Josiah Kibira University (Bukoba)",
"Arch Bishop James University (Ruvuma)",
"Marian University College MARUCo University (Bagamoyo)",
"St. Joseph University College of Health and Allied Sciences SJUCHAS University (Dar es Salaam)",
"Cardinal Rugambwa Memorial University College CARUMUCo University (Bukoba)",
"Institute of Marine Sciences IMS University (Zanzibar)",
"Mzumbe University (Dar es Salaam)",
"Mzumbe University (Mbeya)", 
"Arusha Centre JKUAT Foreign University (Arusha)",
"St. Augustine University of Tanzania (Dar es Salaam)",
"Stefano Moshi Memorial University College (Moshi)",
"St. Augustine University of Tanzania (Arusha) ",
"St Augustine University of Tanzania (Mbeya)" ,
"Teofilo Kisanji University (Dar es Salaam)", 

]

